# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

del2d_constrained_cpp <- function(pts, edges) {
    .Call(`_cdt_del2d_constrained_cpp`, pts, edges)
}

